name: "Nix"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64-linux
          - os: ubuntu-latest
            arch: aarch64-linux
          - os: macos-latest
            arch: x86_64-darwin
    name: Build Nix - ${{ matrix.arch }}.${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup emulation
        if: ${{ matrix.arch == 'aarch64-linux' }}
        run: |
          sudo apt install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
          mkdir -p ~/.config/nix
          echo "system-features = aarch64-linux arm-linux" | sudo tee -a /etc/nix/nix.conf
      - uses: cachix/cachix-action@v12
        with:
          name: unblob
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          nix flake check -L --option system ${{ matrix.arch }} --extra-platforms ${{ matrix.arch }}
      - run: |
          nix build -L --option system ${{ matrix.arch }} --extra-platforms ${{ matrix.arch }}
